// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiGbz7OcG7Drl8aZX4m6uvtCq-hcdYBw',
    appId: '1:699276232169:web:7b225a52837fc732bc7778',
    messagingSenderId: '699276232169',
    projectId: 'flutter-auth-33fb8',
    authDomain: 'flutter-auth-33fb8.firebaseapp.com',
    storageBucket: 'flutter-auth-33fb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9wqvJSnZSvUbrBVrtzGfioltMFBRlOr0',
    appId: '1:699276232169:android:d9c0bf3beb187582bc7778',
    messagingSenderId: '699276232169',
    projectId: 'flutter-auth-33fb8',
    storageBucket: 'flutter-auth-33fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM52fqPAIL9rR4EQmlnvLE0XkgNVWtfPA',
    appId: '1:699276232169:ios:89e0292730155b44bc7778',
    messagingSenderId: '699276232169',
    projectId: 'flutter-auth-33fb8',
    storageBucket: 'flutter-auth-33fb8.appspot.com',
    iosClientId: '699276232169-1qv7eqtishio5g9la6fee5luhro6b7fk.apps.googleusercontent.com',
    iosBundleId: 'io.github.imobasshir.flutterAuth',
  );
}
